# Amount of time a player will see the popup when they join (In seconds)
Time: 30

# Show how many players are on the server?
PlayerCount: true

# Message that will be displayer via Popup
Message: ยง3Welcome ยง6To ยง4The ยง9Server!
